export interface MarqueeItem {
  type: "image" | "text";
  src?: string;
  alt?: string;
  label?: string;
}

export const marqueeDataMap: Record<string, MarqueeItem[]> = {
  "/": [
    { type: "image", src: "/images/services/checkups-prevention.webp", alt: "Annual checkups and preventive care" },
    { type: "text", label: "Primary Care" },
    { type: "image", src: "/images/services/chronic-disease.webp", alt: "Chronic disease management" },
    { type: "text", label: "Naples, FL" },
    { type: "image", src: "/images/services/same-day-visits.webp", alt: "Same-day urgent visits" },
    { type: "text", label: "Palliative Care" },
    { type: "image", src: "/images/services/womens-health.webp", alt: "Women's health services" },
    { type: "text", label: "Senior Care" },
    { type: "image", src: "/images/services/senior-care.webp", alt: "Specialized senior care" },
    { type: "text", label: "Same-Day Visits" },
    { type: "image", src: "/images/services/pain-comfort-management.webp", alt: "Pain and comfort management" },
    { type: "text", label: "Southwest Florida" },
  ],
  "/es": [
    { type: "image", src: "/images/services/checkups-prevention.webp", alt: "Chequeos anuales y atención preventiva" },
    { type: "text", label: "Atención Primaria" },
    { type: "image", src: "/images/services/chronic-disease.webp", alt: "Control de enfermedades crónicas" },
    { type: "text", label: "Naples, FL" },
    { type: "image", src: "/images/services/same-day-visits.webp", alt: "Citas urgentes el mismo día" },
    { type: "text", label: "Cuidados Paliativos" },
    { type: "image", src: "/images/services/womens-health.webp", alt: "Servicios de salud de la mujer" },
    { type: "text", label: "Adultos Mayores" },
    { type: "image", src: "/images/services/senior-care.webp", alt: "Atención especializada para adultos mayores" },
    { type: "text", label: "Citas el Mismo Día" },
    { type: "image", src: "/images/services/pain-comfort-management.webp", alt: "Manejo del dolor y confort" },
    { type: "text", label: "Suroeste de Florida" },
  ],
  "/primary-care/checkups-prevention": [
    { type: "image", src: "/images/services/checkups-prevention.webp", alt: "Annual physical exam" },
    { type: "text", label: "Annual Physicals" },
    { type: "image", src: "/images/services/senior-care.webp", alt: "Medicare wellness visit" },
    { type: "text", label: "Cancer Screenings" },
    { type: "image", src: "/images/services/womens-health.webp", alt: "Health screenings for women" },
    { type: "text", label: "Immunizations" },
    { type: "image", src: "/images/services/chronic-disease.webp", alt: "Risk assessment and prevention" },
    { type: "text", label: "Heart Health" },
    { type: "image", src: "/images/services/in-office-procedures.webp", alt: "In-office lab work" },
    { type: "text", label: "Naples, FL" },
  ],
  "/primary-care/chronic-disease": [
    { type: "image", src: "/images/services/chronic-disease.webp", alt: "Chronic disease management" },
    { type: "text", label: "Diabetes Care" },
    { type: "image", src: "/images/services/checkups-prevention.webp", alt: "Blood pressure monitoring" },
    { type: "text", label: "Heart Disease" },
    { type: "image", src: "/images/services/senior-care.webp", alt: "Senior chronic care" },
    { type: "text", label: "COPD Management" },
    { type: "image", src: "/images/services/in-office-procedures.webp", alt: "Lab monitoring" },
    { type: "text", label: "Thyroid Care" },
    { type: "image", src: "/images/services/same-day-visits.webp", alt: "Follow-up visits" },
    { type: "text", label: "Naples, FL" },
  ],
  "/primary-care/same-day-visits": [
    { type: "image", src: "/images/services/same-day-visits.webp", alt: "Same-day doctor visit" },
    { type: "text", label: "Urgent Care" },
    { type: "image", src: "/images/services/checkups-prevention.webp", alt: "Quick diagnosis" },
    { type: "text", label: "Infections & Flu" },
    { type: "image", src: "/images/services/in-office-procedures.webp", alt: "In-office treatment" },
    { type: "text", label: "Minor Injuries" },
    { type: "image", src: "/images/services/chronic-disease.webp", alt: "Medication review" },
    { type: "text", label: "No ER Needed" },
    { type: "image", src: "/images/services/senior-care.webp", alt: "Senior urgent visit" },
    { type: "text", label: "Naples, FL" },
  ],
  "/primary-care/womens-health": [
    { type: "image", src: "/images/services/womens-health.webp", alt: "Women's health care" },
    { type: "text", label: "Pap Smears" },
    { type: "image", src: "/images/services/checkups-prevention.webp", alt: "Breast examination" },
    { type: "text", label: "Menopause Care" },
    { type: "image", src: "/images/services/chronic-disease.webp", alt: "Hormone health" },
    { type: "text", label: "Contraception" },
    { type: "image", src: "/images/services/in-office-procedures.webp", alt: "Women's health screenings" },
    { type: "text", label: "STI Evaluation" },
    { type: "image", src: "/images/services/senior-care.webp", alt: "Women's preventive care" },
    { type: "text", label: "Naples, FL" },
  ],
  "/primary-care/senior-care": [
    { type: "image", src: "/images/services/senior-care.webp", alt: "Senior geriatric care" },
    { type: "text", label: "Geriatric Care" },
    { type: "image", src: "/images/services/checkups-prevention.webp", alt: "Fall prevention screening" },
    { type: "text", label: "Fall Prevention" },
    { type: "image", src: "/images/services/chronic-disease.webp", alt: "Memory screening" },
    { type: "text", label: "Memory Screening" },
    { type: "image", src: "/images/services/in-office-procedures.webp", alt: "Medication review" },
    { type: "text", label: "Medication Review" },
    { type: "image", src: "/images/services/pain-comfort-management.webp", alt: "Senior comfort care" },
    { type: "text", label: "Naples, FL" },
  ],
  "/primary-care/procedures-diagnostics": [
    { type: "image", src: "/images/services/in-office-procedures.webp", alt: "In-office procedures" },
    { type: "text", label: "Joint Injections" },
    { type: "image", src: "/images/services/checkups-prevention.webp", alt: "EKG testing" },
    { type: "text", label: "Skin Biopsies" },
    { type: "image", src: "/images/services/chronic-disease.webp", alt: "Lab diagnostics" },
    { type: "text", label: "Wound Care" },
    { type: "image", src: "/images/services/same-day-visits.webp", alt: "Rapid lab results" },
    { type: "text", label: "EKG Testing" },
    { type: "image", src: "/images/services/senior-care.webp", alt: "Minor surgical procedures" },
    { type: "text", label: "Naples, FL" },
  ],
  "/palliative-care/about-palliative-care": [
    { type: "image", src: "/images/services/pain-comfort-management.webp", alt: "Palliative care consultation" },
    { type: "text", label: "Not Hospice" },
    { type: "image", src: "/images/services/patient-family-support.webp", alt: "Family support" },
    { type: "text", label: "Quality of Life" },
    { type: "image", src: "/images/services/symptom-relief.webp", alt: "Symptom relief" },
    { type: "text", label: "Any Stage" },
    { type: "image", src: "/images/services/planning-transitions.webp", alt: "Care planning" },
    { type: "text", label: "Alongside Treatment" },
    { type: "image", src: "/images/services/senior-care.webp", alt: "Compassionate care" },
    { type: "text", label: "Naples, FL" },
  ],
  "/palliative-care/symptom-relief": [
    { type: "image", src: "/images/services/symptom-relief.webp", alt: "Symptom management" },
    { type: "text", label: "Pain Relief" },
    { type: "image", src: "/images/services/pain-comfort-management.webp", alt: "Comfort care" },
    { type: "text", label: "Breathing Support" },
    { type: "image", src: "/images/services/chronic-disease.webp", alt: "Fatigue management" },
    { type: "text", label: "Nausea Relief" },
    { type: "image", src: "/images/services/patient-family-support.webp", alt: "Emotional support" },
    { type: "text", label: "Better Sleep" },
    { type: "image", src: "/images/services/senior-care.webp", alt: "Senior symptom care" },
    { type: "text", label: "Naples, FL" },
  ],
  "/palliative-care/patient-family-support": [
    { type: "image", src: "/images/services/patient-family-support.webp", alt: "Family support meeting" },
    { type: "text", label: "Caregiver Support" },
    { type: "image", src: "/images/services/pain-comfort-management.webp", alt: "Patient comfort" },
    { type: "text", label: "Family Meetings" },
    { type: "image", src: "/images/services/planning-transitions.webp", alt: "Care planning with family" },
    { type: "text", label: "Emotional Care" },
    { type: "image", src: "/images/services/senior-care.webp", alt: "Senior family care" },
    { type: "text", label: "Community Resources" },
    { type: "image", src: "/images/services/symptom-relief.webp", alt: "Ongoing support" },
    { type: "text", label: "Naples, FL" },
  ],
  "/palliative-care/planning-transitions": [
    { type: "image", src: "/images/services/planning-transitions.webp", alt: "Advance care planning" },
    { type: "text", label: "Advance Directives" },
    { type: "image", src: "/images/services/patient-family-support.webp", alt: "Family discussion" },
    { type: "text", label: "Living Wills" },
    { type: "image", src: "/images/services/pain-comfort-management.webp", alt: "Goals of care" },
    { type: "text", label: "Goals of Care" },
    { type: "image", src: "/images/services/symptom-relief.webp", alt: "Hospice coordination" },
    { type: "text", label: "Hospice Coordination" },
    { type: "image", src: "/images/services/senior-care.webp", alt: "Senior planning" },
    { type: "text", label: "Naples, FL" },
  ],
  "/locations/fort-myers": [
    { type: "image", src: "/images/services/checkups-prevention.webp", alt: "Preventive care in Fort Myers" },
    { type: "text", label: "Fort Myers, FL" },
    { type: "image", src: "/images/services/chronic-disease.webp", alt: "Chronic disease management in Fort Myers" },
    { type: "text", label: "Primary Care" },
    { type: "image", src: "/images/services/same-day-visits.webp", alt: "Same-day visits in Fort Myers" },
    { type: "text", label: "35 min via I-75" },
    { type: "image", src: "/images/services/senior-care.webp", alt: "Senior care services in Fort Myers" },
    { type: "text", label: "Senior Care" },
    { type: "image", src: "/images/services/in-office-procedures.webp", alt: "In-office procedures in Fort Myers" },
    { type: "text", label: "Same-Day Visits" },
  ],
  "/locations/cape-coral": [
    { type: "image", src: "/images/services/checkups-prevention.webp", alt: "Preventive care in Cape Coral" },
    { type: "text", label: "Cape Coral, FL" },
    { type: "image", src: "/images/services/womens-health.webp", alt: "Women's health services in Cape Coral" },
    { type: "text", label: "New Patients Welcome" },
    { type: "image", src: "/images/services/chronic-disease.webp", alt: "Chronic disease management in Cape Coral" },
    { type: "text", label: "Primary Care" },
    { type: "image", src: "/images/services/pain-comfort-management.webp", alt: "Palliative care in Cape Coral" },
    { type: "text", label: "Palliative Care" },
    { type: "image", src: "/images/services/senior-care.webp", alt: "Senior care in Cape Coral" },
    { type: "text", label: "Medicare Accepted" },
  ],
  "/locations/bonita-springs": [
    { type: "image", src: "/images/services/checkups-prevention.webp", alt: "Preventive care in Bonita Springs" },
    { type: "text", label: "Bonita Springs, FL" },
    { type: "image", src: "/images/services/same-day-visits.webp", alt: "Same-day visits in Bonita Springs" },
    { type: "text", label: "15 min on US-41" },
    { type: "image", src: "/images/services/chronic-disease.webp", alt: "Primary care in Bonita Springs" },
    { type: "text", label: "Primary Care" },
    { type: "image", src: "/images/services/senior-care.webp", alt: "Senior care in Bonita Springs" },
    { type: "text", label: "Senior Care" },
    { type: "image", src: "/images/services/in-office-procedures.webp", alt: "In-office procedures in Bonita Springs" },
    { type: "text", label: "Same-Day Visits" },
  ],
  "/locations/estero": [
    { type: "image", src: "/images/services/checkups-prevention.webp", alt: "Preventive care in Estero" },
    { type: "text", label: "Estero, FL" },
    { type: "image", src: "/images/services/chronic-disease.webp", alt: "Chronic disease management in Estero" },
    { type: "text", label: "20 min on US-41" },
    { type: "image", src: "/images/services/same-day-visits.webp", alt: "Same-day visits in Estero" },
    { type: "text", label: "Primary Care" },
    { type: "image", src: "/images/services/in-office-procedures.webp", alt: "In-office procedures in Estero" },
    { type: "text", label: "In-Office Procedures" },
    { type: "image", src: "/images/services/senior-care.webp", alt: "Senior care in Estero" },
    { type: "text", label: "Medicare Accepted" },
  ],
  "/locations/marco-island": [
    { type: "image", src: "/images/services/senior-care.webp", alt: "Senior care on Marco Island" },
    { type: "text", label: "Marco Island, FL" },
    { type: "image", src: "/images/services/checkups-prevention.webp", alt: "Geriatric care on Marco Island" },
    { type: "text", label: "Geriatric Care" },
    { type: "image", src: "/images/services/pain-comfort-management.webp", alt: "Palliative care on Marco Island" },
    { type: "text", label: "25 min via Collier Blvd" },
    { type: "image", src: "/images/services/symptom-relief.webp", alt: "Symptom relief on Marco Island" },
    { type: "text", label: "Palliative Care" },
    { type: "image", src: "/images/services/patient-family-support.webp", alt: "Patient support on Marco Island" },
    { type: "text", label: "Senior Care" },
  ],
  "/locations/golden-gate": [
    { type: "image", src: "/images/services/checkups-prevention.webp", alt: "Preventive care in Golden Gate" },
    { type: "text", label: "Golden Gate, FL" },
    { type: "image", src: "/images/services/womens-health.webp", alt: "Bilingual health services in Golden Gate" },
    { type: "text", label: "Bilingual Care" },
    { type: "image", src: "/images/services/chronic-disease.webp", alt: "Primary care in Golden Gate" },
    { type: "text", label: "15 min Drive" },
    { type: "image", src: "/images/services/same-day-visits.webp", alt: "Same-day visits in Golden Gate" },
    { type: "text", label: "Primary Care" },
    { type: "image", src: "/images/services/senior-care.webp", alt: "Senior care in Golden Gate" },
    { type: "text", label: "Medicaid Accepted" },
  ],
  "/locations/immokalee": [
    { type: "image", src: "/images/services/checkups-prevention.webp", alt: "Preventive care in Immokalee" },
    { type: "text", label: "Immokalee, FL" },
    { type: "image", src: "/images/services/chronic-disease.webp", alt: "Primary care in Immokalee" },
    { type: "text", label: "Collier County" },
    { type: "image", src: "/images/services/same-day-visits.webp", alt: "Same-day visits in Immokalee" },
    { type: "text", label: "Primary Care" },
    { type: "image", src: "/images/services/womens-health.webp", alt: "Preventive health services in Immokalee" },
    { type: "text", label: "Preventive Care" },
    { type: "image", src: "/images/services/senior-care.webp", alt: "Senior care in Immokalee" },
    { type: "text", label: "Medicare & Medicaid" },
  ],
};
