"use client";
import {useState} from "react";
import type {Post} from "../../../server/blog/types";
const states=[["all","All articles"],["published","Published"],["pending_review","Pending review"],["draft","Drafts"],["rejected","Rejected"]] as const;
export default function Dashboard({posts,generating,onGenerate,onNew,onSelect}:{posts:Post[];generating:boolean;onGenerate:()=>void;onNew:()=>void;onSelect:(post:Post)=>void}){
 const [search,setSearch]=useState(""),[status,setStatus]=useState("all"),[language,setLanguage]=useState("all");
 const visible=posts.filter(p=>(status==="all"||p.status===status)&&(language==="all"||p.language===language)&&[p.title,p.slug,p.data.category,...p.data.tags].join(" ").toLowerCase().includes(search.toLowerCase()));
 return <><header className="dashboard-heading"><div><p className="blog-eyebrow">FAITHFUL CARE EDITORIAL STUDIO</p><h1>Blog management</h1><p>Helpful patient education, from the first idea to a reviewed article.</p></div><div className="editor-actions"><button onClick={onGenerate}>{generating?"View generation progress":"Auto Generate"}</button><button className="secondary" onClick={onNew}>New draft</button></div></header>
 <div className="dashboard-stats" aria-label="Article counts">{states.map(([key,label])=><button key={key} className="stat-card" aria-pressed={status===key} onClick={()=>setStatus(key)}><span>{key==="all"?"Total articles":label}</span><strong>{key==="all"?posts.length:posts.filter(p=>p.status===key).length}</strong></button>)}</div>
 <section className="dashboard-library" aria-label="Articles"><div className="dashboard-filters"><label>Search articles<input type="search" placeholder="Search titles, topics or tags" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Article language<select value={language} onChange={e=>setLanguage(e.target.value)}><option value="all">Both languages</option><option value="en">English</option><option value="es">Español</option></select></label></div><div className="status-filters" aria-label="Filter by editorial status">{states.map(([key,label])=><button key={key} className="secondary" aria-pressed={status===key} onClick={()=>setStatus(key)}>{label}</button>)}</div>
 <div className="article-table-head" aria-hidden><span>Article</span><span>Status</span><span>Updated</span><span>Actions</span></div>
 <div className="article-list">{visible.map(p=><article className="article-row" key={p.id}><div className="article-row-title">{p.data.hero?<img src={p.data.hero} alt="" loading="lazy"/>:<div className="article-image-placeholder" aria-hidden>FC</div>}<div><small>{p.language.toUpperCase()} · {p.data.category.replaceAll("-"," ")}</small><h2><button className="article-title-button" onClick={()=>onSelect(p)}>{p.title}</button></h2><p>{p.data.excerpt}</p></div></div><span className={"status-badge status-"+p.status}>{p.status.replaceAll("_"," ")}</span><time dateTime={p.updated_at}>{new Date(p.updated_at).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"})}</time><div className="article-row-actions"><button className="secondary" onClick={()=>onSelect(p)}>Review article</button>{p.status==="published"&&<a target="_blank" rel="noreferrer" href={(p.language==="es"?"/es":"")+"/blog/"+p.slug}>View published ↗</a>}</div></article>)}</div>
 {!visible.length&&<div className="dashboard-empty"><h2>{posts.length?"No articles match these filters":"Your patient resource library starts here"}</h2><p>{posts.length?"Try another search, language or status.":"Use Auto Generate to prepare an article and its translation, or begin with a new draft."}</p></div>}<p className="dashboard-count">{visible.length} of {posts.length} articles · Translations are reviewed separately.</p></section></>;
}
