"use client";
import {useState} from "react";
import type {Post,Status} from "../../../server/blog/types";
import {matchesSearch} from "../../../shared/blog-search";
import SeoPanel from "./seo-panel";
const states=[["all","All articles"],["published","Published"],["pending_review","Pending review"],["draft","Drafts"],["rejected","Rejected"]] as const;
type Report={words:number;blockers:string[];warnings:string[]};
export default function Dashboard({posts,generating,onGenerate,onNew,onSelect,onEdit,onState,api}:{posts:Post[];generating:boolean;onGenerate:()=>void;onNew:()=>void;onSelect:(post:Post)=>void;onEdit:(post:Post)=>void;onState:(post:Post,status:Status)=>Promise<void>;api:(path:string,method?:string,body?:unknown)=>Promise<any>}){
 const [search,setSearch]=useState(""),[status,setStatus]=useState("all"),[language,setLanguage]=useState("all"),[manage,setManage]=useState<string|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const [report,setReport]=useState<Report|null>(null);
 const visible=posts.filter(p=>(status==="all"||p.status===status)&&(language==="all"||p.language===language)&&matchesSearch([p.title,p.slug,p.data.topic,p.data.category,...p.data.tags],search));
 async function act(fn:()=>Promise<void>){setBusy(true);setMessage("");setReport(null);try{await fn();}catch(e){setMessage(e instanceof Error?e.message:"Action failed.");}finally{setBusy(false);}}
 return <><header className="dashboard-heading"><div><p className="blog-eyebrow">FAITHFUL CARE EDITORIAL STUDIO</p><h1>Blog management</h1><p>Prepare an article, read its preview and publish when it is ready.</p></div><div className="editor-actions"><button onClick={onGenerate}>{generating?"View generation progress":"Auto Generate"}</button><button className="secondary" onClick={onNew}>New draft</button></div></header>
 <div className="dashboard-stats" aria-label="Article counts">{states.map(([key,label])=><button key={key} className="stat-card" aria-pressed={status===key} onClick={()=>setStatus(key)}><span>{key==="all"?"Total articles":label}</span><strong>{key==="all"?posts.length:posts.filter(p=>p.status===key).length}</strong></button>)}</div>
 <section className="dashboard-library" aria-label="Articles"><div className="dashboard-filters"><label>Search articles<input type="search" placeholder="Search titles, topics or tags" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Article language<select value={language} onChange={e=>setLanguage(e.target.value)}><option value="all">Both languages</option><option value="en">English</option><option value="es">Español</option></select></label></div><div className="status-filters" aria-label="Filter by editorial status">{states.map(([key,label])=><button key={key} className="secondary" aria-pressed={status===key} onClick={()=>setStatus(key)}>{label}</button>)}</div>
 <div className="article-table-head" aria-hidden><span>Article</span><span>Status</span><span>Updated</span><span>Actions</span></div>
 <div className="article-list">{visible.map(p=><article className="article-row" key={p.id} aria-label={p.title}><div className="article-row-title">{p.data.hero?<img src={p.data.hero} alt="" loading="lazy"/>:<div className="article-image-placeholder" aria-hidden>FC</div>}<div><small>{p.language.toUpperCase()} · {p.data.category.replaceAll("-"," ")}</small><h2><button className="article-title-button" onClick={()=>onSelect(p)}>{p.title}</button></h2><p>{p.data.excerpt}</p></div></div><span className={"status-badge status-"+p.status}>{p.status.replaceAll("_"," ")}</span><time dateTime={p.updated_at}>{new Date(p.updated_at).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"})}</time><div className="article-row-actions"><button className="secondary article-action-icon" aria-label="Preview" title="Preview article" onClick={()=>onSelect(p)}><svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></svg></button><button className="secondary article-action-icon" aria-label="Edit" title="Edit article" onClick={()=>onEdit(p)}><svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="m16 3 5 5M4 20l5-1L21 7a2.8 2.8 0 0 0-4-4L5 15l-1 5Z"/></svg></button><button className="secondary article-action-icon" aria-label="Manage" title="Publication and article checks" disabled={busy} aria-expanded={manage===p.id} aria-controls={"manage-"+p.id} onClick={()=>{setManage(manage===p.id?null:p.id);setMessage("");setReport(null);}}><svg aria-hidden="true" viewBox="0 0 24 24" fill="currentColor"><circle cx="5" cy="12" r="2"/><circle cx="12" cy="12" r="2"/><circle cx="19" cy="12" r="2"/></svg></button></div>
 {manage===p.id&&<section id={"manage-"+p.id} className="row-management" aria-label="Publication controls"><div><h3>Publication</h3><p>Publish this language version or keep it as a private draft.</p></div><div className="editor-actions"><button className="secondary" disabled={busy||generating} onClick={()=>act(async()=>setReport(await api("posts/"+p.id+"/verify","POST",{})))}>Check article</button>{p.status==="draft"&&<button className="secondary" disabled={busy||generating} onClick={()=>act(async()=>{await onState(p,"pending_review");setMessage("Moved to pending review.");})}>Send to review</button>}{["draft","pending_review"].includes(p.status)&&<button disabled={busy||generating} onClick={()=>act(async()=>{await onState(p,"published");setMessage("Article published.");})}>Publish</button>}{p.status!=="draft"&&<button className="secondary" disabled={busy||generating} onClick={()=>act(async()=>{if(p.status==="published"){const {articles}=await api("posts/"+p.id+"/incoming-links");if(articles.length&&!window.confirm("Unpublish this article? "+articles.length+" published article(s) link to it:\n\n"+articles.map((article:{title:string})=>article.title).join("\n")+"\n\nThose links will stop working. Update them after unpublishing."))return;}await onState(p,"draft");setMessage("Returned to draft. The article is private.");})}>{p.status==="published"?"Unpublish":"Return to draft"}</button>}{p.status==="published"&&<a target="_blank" rel="noreferrer" href={(p.language==="es"?"/es":"")+"/blog/"+p.slug}>View published ↗</a>}</div>
 {busy&&<p role="status">Checking and saving…</p>}{message&&<p role="status" className="editor-message">{message}</p>}{report&&<div className="publication-report"><h4>Article checks · {report.words} words</h4>{report.blockers.length?<ul>{report.blockers.map(b=><li key={b}>{b}</li>)}</ul>:<p>Publication checks passed.</p>}{report.warnings.map(w=><p key={w}>{w}</p>)}</div>}<SeoPanel id={p.id} version={p.version} published={p.status==="published"} api={api}/></section>}</article>)}</div>
 {!visible.length&&<div className="dashboard-empty"><h2>{posts.length?"No articles match these filters":"Your patient resource library starts here"}</h2><p>{posts.length?"Try another search, language or status.":"Use Auto Generate to prepare an article and its translation, or begin with a new draft."}</p></div>}<p className="dashboard-count">{visible.length} of {posts.length} articles · Each language is published separately.</p></section></>;
}
