"use client";
import {useEffect,useRef,useState} from "react";
import {googleEvidence,type GoogleEvent} from "../../../shared/blog-google-status";
const date=(value?:string)=>value?new Date(value).toLocaleString():"No recorded check";
export default function SeoPanel({id,url,version,published,api}:{id:string;url:string;version:number;published:boolean;api:(path:string,method?:string,body?:unknown)=>Promise<any>}){
 const [events,setEvents]=useState<GoogleEvent[]>([]),[enabled,setEnabled]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const generation=useRef(0),apiRef=useRef(api);apiRef.current=api;
 useEffect(()=>{const request=++generation.current;setEvents([]);setEnabled(false);setLoading(true);setBusy(false);setMessage("");apiRef.current("posts/"+id+"/seo").then(d=>{if(request===generation.current){setEvents(d.events);setEnabled(d.enabled);}}).catch(e=>{if(request===generation.current)setMessage(e.message);}).finally(()=>{if(request===generation.current)setLoading(false);});return()=>{generation.current++;};},[id,version]);
 async function check(){const request=generation.current;setBusy(true);setMessage("");try{const result=await api("posts/"+id+"/seo","POST",{});const data=await api("posts/"+id+"/seo");if(request===generation.current){setEvents(data.events);setEnabled(data.enabled);setMessage(result.reason||result.error||"Google check complete. See the dated results below.");}}catch(e){if(request===generation.current)setMessage(e instanceof Error?e.message:"Check failed.");}finally{if(request===generation.current)setBusy(false);}}
 const evidence=googleEvidence(events,url),inspection=evidence.inspection?.detail.inspection;
 return <details className="google-visibility"><summary>Google visibility and publishing checks</summary>
 <p>Check the published page, send its sitemap and read Google's last indexed data. These are separate steps; submitting a sitemap does not request indexing for an individual URL.</p>
 <div className="google-actions"><button className="secondary" disabled={loading||busy||!published||!enabled} onClick={check}>{busy?"Checking Google…":"Check Google status"}</button><a className="secondary" href={evidence.consoleUrl} target="_blank" rel="noopener noreferrer">Open in Search Console ↗</a><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(url);setMessage("Article URL copied.");}catch{setMessage("Copy the article URL shown below.");}}}>Copy article URL</button></div>
 <p className="google-article-url">{url}</p>
 {loading&&<p role="status">Loading Google evidence…</p>}{!loading&&!enabled&&<p>Google checks are unavailable in this deployment. Preview never submits articles; production requires an enabled Google connection.</p>}{!published&&<p>Publish this language version before checking its public URL.</p>}
 {message&&<p role="status">{message}</p>}
 {evidence.latest?.detail.status==="failed"&&<p role="alert">Latest check failed: {evidence.latest.detail.error} Previous results below remain historical evidence.</p>}
 <div className="google-evidence">
 <article><h4>Sitemap submission</h4><strong>{evidence.submission?"Accepted by Google":"No confirmed submission"}</strong><p>{evidence.submission?"Last recorded: "+date(evidence.submission.detail.sitemapSubmittedAt||evidence.submission.created_at):"No successful submission is recorded for this URL in the recent history."}</p><p>This is a sitemap receipt, not an individual indexing request.</p></article>
 <article><h4>Google index status</h4><strong>{evidence.indexLabel}</strong><p>{inspection?.coverageState||"Run a check to read Google's response."}</p><p>Last inspected: {date(evidence.inspection?.detail.inspectedAt||evidence.inspection?.created_at)}</p>{inspection?.lastCrawlTime&&<p>Google last crawled: {date(inspection.lastCrawlTime)}</p>}<p>This reflects Google's stored version, which may differ from the current article.</p></article>
 <article><h4>Individual indexing request</h4><strong>Managed in Search Console</strong><p>Open Search Console, inspect the article URL and select <b>Request indexing</b> if Google offers it. Google shows the confirmation there.</p><p>Google's API does not let this dashboard request or verify that manual submission. Opening the link does not submit a request.</p></article>
 </div>
 <details className="google-history"><summary>Recent checks ({events.length})</summary>{events.map((e,i)=><article key={i} className="editor-report"><strong>{e.action.replaceAll("_"," ")} · {date(e.created_at)}</strong><p>{e.detail.reason||e.detail.error||e.detail.note}</p>{e.detail.articleVersion&&<p>Checked article version: {e.detail.articleVersion}{e.detail.articleVersion!==version?" (earlier version)":""}</p>}<p>Live page checks: {e.detail.audit?.ok?"passed":"not confirmed"} · Sitemap submitted: {e.detail.sitemapSubmitted?"yes":"no"}</p>{e.detail.inspection&&<p>{e.detail.inspection.coverageState||e.detail.inspection.verdict||"Unknown"}</p>}</article>)}</details>
 </details>;
}
