"use client";
import {useEffect,useState} from "react";
type Source={url:string;title:string;categories:string[];publisher:string;score:number;reason:string;approved:boolean;health:string;http_status:number|null;checked_at:string|null;cache_expires_at:string|null;usage:number;articles:{id:string;title:string;language:string;status:string}[]};
type Entry={id:string;action:string;created_at:string;detail:{url?:string;health?:string;score?:number;status?:number}};
const date=(v:string|null)=>v?new Date(v).toLocaleString():"Not yet";
export default function Sources({api}:{api:(path:string,method?:string,body?:unknown)=>Promise<any>}){
 const [sources,setSources]=useState<Source[]>([]),[history,setHistory]=useState<Entry[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[tab,setTab]=useState("library"),[search,setSearch]=useState(""),[filter,setFilter]=useState("all");
 async function load(){const d=await api("links/dashboard");setSources(d.links);setHistory(d.history);}
 useEffect(()=>{load().catch(e=>setMessage(e.message));},[]);
 async function act(action:()=>Promise<void>){setBusy(true);setMessage("");try{await action();await load();}catch(e){setMessage(e instanceof Error?e.message:"Check failed.");}finally{setBusy(false);}}
 const visible=sources.filter(s=>(filter==="all"||filter==="approved"&&s.approved||filter==="needs-review"&&!s.approved||filter==="unhealthy"&&s.health!=="healthy")&&[s.title,s.url,...s.categories].join(" ").toLowerCase().includes(search.toLowerCase()));
 return <section className="source-workspace"><header className="section-heading"><div><p className="blog-eyebrow">RESEARCH & CITATIONS</p><h2>Sources and link health</h2><p>Inspect the exact pages consulted, their quality checks and the articles that cite them.</p></div><button disabled={busy||!sources.length} className="secondary" onClick={()=>act(async()=>{for(const s of sources)await api("links/check","POST",{url:s.url});setMessage("Live checks completed. Review the results before approving sources.");})}>Check all sources</button></header>
 <div className="source-stats"><div><strong>{sources.length}</strong><span>Curated sources</span></div><div><strong>{sources.filter(s=>s.health==="healthy").length}</strong><span>Healthy at last check</span></div><div><strong>{sources.filter(s=>s.approved).length}</strong><span>Approved</span></div><div><strong>{sources.filter(s=>s.cache_expires_at&&Date.parse(s.cache_expires_at)>Date.now()).length}</strong><span>Fresh research copies</span></div></div>
 <div className="status-filters" aria-label="Source views">{[["library","Source library"],["history","Consultation history"]].map(([key,label])=><button key={key} className="secondary" aria-pressed={tab===key} onClick={()=>setTab(key)}>{label}</button>)}</div>
 {message&&<p role="status" className="editor-message">{message}</p>}{busy&&<p role="status">Checking sources… Each result is saved.</p>}
 {tab==="library"?<><div className="dashboard-filters"><label>Search sources<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Topic, source or URL"/></label><label>Source status<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All sources</option><option value="approved">Approved</option><option value="needs-review">Needs approval</option><option value="unhealthy">Needs a health check</option></select></label></div><div className="source-grid">{visible.map(s=><article key={s.url} className="source-card"><div className="source-card-heading"><h3><a href={s.url} target="_blank" rel="noreferrer">{s.title} ↗</a></h3><span className={"status-badge "+(s.health==="healthy"?"status-published":"status-pending_review")}>{s.health}</span></div><p className="source-publisher">{s.publisher}</p><p className="source-url">{s.url}</p><div className="source-quality"><strong>{s.score}<small>/100</small></strong><span>Source quality<br/>{s.approved?"Approved for citation":"Approval required"}</span></div><p className="source-categories">{s.categories.map(c=>c.replaceAll("-"," ")).join(" · ")}</p><dl className="source-facts"><div><dt>Live check</dt><dd>{date(s.checked_at)}{s.http_status?" · HTTP "+s.http_status:""}</dd></div><div><dt>Research copy expires</dt><dd>{date(s.cache_expires_at)}</dd></div><div><dt>Used in articles</dt><dd>{s.usage}</dd></div></dl><details><summary>Quality breakdown and citations</summary><p>{s.reason}</p>{s.articles.length?<ul>{s.articles.map(p=><li key={p.id}>{p.title} · {p.language.toUpperCase()} · {p.status.replaceAll("_"," ")}</li>)}</ul>:<p>No saved articles cite this source yet.</p>}</details><div className="editor-actions"><button disabled={busy} className="secondary" onClick={()=>act(async()=>{await api("links/check","POST",{url:s.url});})}>Check live URL</button><button disabled={busy||(!s.approved&&s.health!=="healthy")} className="secondary" onClick={()=>act(async()=>{await api("links/approve","POST",{url:s.url,approved:!s.approved});})}>{s.approved?"Block source":"Approve source"}</button></div></article>)}</div>{!visible.length&&<p className="dashboard-empty">No sources match this filter.</p>}</>:<div className="source-history"><p>Latest 100 checks, research consultations and approval decisions. Research copies last 24 hours; manual health checks always fetch the live page.</p>{history.length?history.map(h=><article key={h.id}><span className="status-badge">{h.action.replaceAll("_"," ")}</span><time>{date(h.created_at)}</time><p>{h.detail.url}</p>{h.detail.health&&<small>{h.detail.health} · Quality {h.detail.score}/100</small>}</article>):<p>No source activity recorded yet.</p>}</div>}
 <p className="source-footnote">A healthy URL and a high source score do not certify a medical claim. Clinical review remains separate. Only curated source URLs can be fetched.</p></section>;
}
