"use client";
import {useEffect,useState} from "react";
import type {Post} from "../../../server/blog/types";
import Generator from "./generator";
import Sources from "./sources";
import {blankData} from "../../../server/blog/types";
type Draft=Pick<Post,"title"|"slug"|"language"|"content"|"data"> & Partial<Post>;
const fresh=():Draft=>({title:"",slug:"",language:"en",content:"",data:{...blankData}});
export default function Editor({username}:{username:string}){
 const [posts,setPosts]=useState<Post[]>([]),[draft,setDraft]=useState<Draft>(fresh),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[reviewer,setReviewer]=useState(""),[reviewed,setReviewed]=useState(false);
 const [dirty,setDirty]=useState(false);
 const [report,setReport]=useState<{blockers:string[];warnings:string[];words:number}|null>(null);
 async function api(path:string,method="GET",body?:unknown){const r=await fetch("/api/admin/blog/"+path,{method,headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});const d=await r.json();if(r.status===401){window.location.href="/admin/login";throw Error("Sign in again.");}if(!r.ok)throw Error(d.error||"Request failed.");return d;}
 async function refresh(){const d=await api("posts");setPosts(d.posts);}
 useEffect(()=>{refresh().catch(e=>setMessage(e.message));},[]);
 function choose(p:Draft){setDirty(false);setDraft(p);setReviewer("");setReviewed(false);setReport(null);setMessage("");}
 function field(key:string,value:unknown){setDirty(true);setDraft(p=>({...p,[key]:value}));setReport(null);setReviewed(false);}
 function data(key:string,value:unknown){setDirty(true);setDraft(p=>({...p,data:{...p.data,[key]:value}}));setReport(null);setReviewed(false);}
 async function run(action:()=>Promise<void>){setBusy(true);setMessage("");try{await action();}catch(e){setMessage(e instanceof Error?e.message:"Request failed.");}finally{setBusy(false);}}
 async function save(){const d=await api(draft.id?"posts/"+draft.id:"posts",draft.id?"PUT":"POST",draft);choose(d.post);setMessage("Draft saved. It remains private.");await refresh();}
 async function state(status:string){if(!draft.id)return;const d=await api("posts/"+draft.id+"/status","POST",{status,version:draft.version,reviewer:reviewed?reviewer:""});choose(d.post);setMessage(status==="published"?"Article published.":"Editorial status updated.");await refresh();}
 const locked=draft.status==="published";
 return <div className="editor"><header className="editor-header"><a href="/">Faithful Care <span>Editorial studio</span></a><div><span>{username}</span><button className="secondary" onClick={()=>run(async()=>{await api("logout","POST",{});window.location.href="/admin/login";})}>Sign out</button></div></header>
 <div className="editor-grid"><aside><div className="editor-list-heading"><h1>Articles</h1><button onClick={()=>choose(fresh())}>New draft</button></div><p>Every useful article begins with a careful review.</p>{posts.length===0&&<p>No articles yet. Create your first draft.</p>}{posts.map(p=><button className={"editor-post "+(draft.id===p.id?"selected":"")} key={p.id} onClick={()=>choose(p)}><span>{p.language.toUpperCase()} · {p.status.replace("_"," ")}</span><strong>{p.title}</strong></button>)}</aside>
 <main><div className="editor-title"><div><p className="blog-eyebrow">{draft.id?"ARTICLE WORKSPACE":"START SOMETHING USEFUL"}</p><h2>{draft.id?draft.title:"A new patient resource"}</h2></div><span className="blog-pill">{draft.status||"draft"}</span></div>
 {dirty&&<p className="editor-message">Save your changes before verification or publication.</p>}
 {message&&<p role="status" className="editor-message">{message}</p>}
 <fieldset disabled={busy||locked}><div className="editor-fields"><label>Title<input value={draft.title} onChange={e=>field("title",e.target.value)}/></label><label>Language<select disabled={!!draft.id} value={draft.language} onChange={e=>field("language",e.target.value)}><option value="en">English</option><option value="es">Español</option></select></label><label>URL slug<input value={draft.slug} onChange={e=>field("slug",e.target.value)}/></label><label>Category<select value={draft.data.category} onChange={e=>data("category",e.target.value)}>{["prevention","primary-care","chronic-care","senior-care","palliative-care","family-support"].map(c=><option key={c}>{c}</option>)}</select></label></div>
 <label>Summary<textarea rows={2} value={draft.data.excerpt} onChange={e=>data("excerpt",e.target.value)}/></label>
 <label>Article HTML<textarea className="editor-code" rows={15} value={draft.content} onChange={e=>field("content",e.target.value)} placeholder="<h2>A helpful section</h2><p>Evidence-based patient education…</p>"/></label>
 <details><summary>Search appearance, sources and media</summary><div className="editor-fields"><label>SEO title<input value={draft.data.metaTitle} onChange={e=>data("metaTitle",e.target.value)}/></label><label>SEO description<input value={draft.data.metaDescription} onChange={e=>data("metaDescription",e.target.value)}/></label><label>Tags (comma separated)<input value={draft.data.tags.join(", ")} onChange={e=>data("tags",e.target.value.split(",").map(s=>s.trim()).filter(Boolean))}/></label><label>Editorial author<input value={draft.data.author} onChange={e=>data("author",e.target.value)}/></label><label>Hero image URL<input value={draft.data.hero} onChange={e=>data("hero",e.target.value)}/></label><label>Hero alternative text<input value={draft.data.heroAlt} onChange={e=>data("heroAlt",e.target.value)}/></label></div><label>Medical sources (one URL per line)<textarea value={draft.data.sources.join("\n")} onChange={e=>data("sources",e.target.value.split("\n").filter(Boolean))}/></label><label>Medical disclaimer<textarea value={draft.data.disclaimer} onChange={e=>data("disclaimer",e.target.value)}/></label></details></fieldset>
 <div className="editor-actions"><button disabled={busy||locked} onClick={()=>run(save)}>Save draft</button>{draft.id&&<><button className="secondary" disabled={busy||dirty} onClick={()=>run(async()=>setReport(await api("posts/"+draft.id+"/verify","POST",{})))}>Check article</button>{draft.status==="draft"&&<button className="secondary" disabled={busy||dirty} onClick={()=>run(()=>state("pending_review"))}>Send to review</button>}{draft.status==="published"&&<><a target="_blank" rel="noreferrer" href={(draft.language==="es"?"/es":"")+"/blog/"+draft.slug}>View article</a><button className="secondary" disabled={busy} onClick={()=>run(()=>state("draft"))}>Unpublish</button></>}</>}</div>
 {report&&<section className="editor-report"><h3>Prepublication checks · {report.words} words</h3>{report.blockers.map((b,i)=><p key={i}>Required: {b}</p>)}{report.warnings.map((w,i)=><p key={i}>Review: {w}</p>)}{!report.blockers.length&&<p>Technical checks passed. Confirm clinical review before publication.</p>}</section>}
 {draft.status==="pending_review"&&<section className="editor-review"><h3>Clinical review</h3><p>Only confirm a review that actually happened. This confirmation is recorded with your editor account.</p><label>Reviewing clinician<input value={reviewer} onChange={e=>setReviewer(e.target.value)}/></label><label className="editor-check"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I confirm the named clinician reviewed this exact saved article.</label><button disabled={busy||dirty||!reviewed||!reviewer.trim()} onClick={()=>run(()=>state("published"))}>Publish reviewed article</button><button className="secondary" disabled={busy} onClick={()=>run(()=>state("draft"))}>Return to draft</button></section>}
 <Generator api={api} onDraft={p=>{choose(p);refresh().catch(e=>setMessage(e.message));}}/><Sources api={api}/></main></div></div>;
}
