import assert from "node:assert/strict";
import fs from "node:fs/promises";
import {chromium} from "playwright";
import sharp from "sharp";
import {CONSENT_STORAGE_KEY,CONSENT_VERSION} from "../shared/tracking.ts";
const config=JSON.parse(await fs.readFile(".local/blog-e2e.json","utf8"));
const browser=await chromium.launch();
await fs.mkdir("artifacts/blog",{recursive:true});
const fixture=await sharp({create:{width:1200,height:750,channels:3,background:"#153d57"}}).webp().toBuffer();
const source="https://medlineplus.gov/healthscreening.html";
const content="<h2>Preparing for a thoughtful visit</h2>"+Array.from({length:65},()=>"<p>LOCAL QA FIXTURE ONLY. Bring your questions and a current medicine list to discuss with your clinician. This paragraph verifies layout and publication controls.</p>").join("")+'<p><a href="/primary-care">Primary care</a> <a href="/contact">Contact</a> <a href="'+source+'">MedlinePlus</a></p><h2>Questions and next steps</h2><p>This is a local technical test, not an approved medical article.</p>';
try{
 for(const [width,height] of [[1440,900],[390,844]]){
  const context=await browser.newContext({viewport:{width,height}});
  const page=await context.newPage(),errors=[],tracking=[];
  page.on("pageerror",e=>{errors.push(e.message);console.log("Browser error:",e.message);});page.on("console",m=>{if(m.type()==="error")errors.push(m.text());});
  context.on("request",r=>{if(/googletagmanager|google-analytics|clarity\.ms/.test(r.url()))tracking.push(r.url());});
  await page.goto(config.baseUrl+"/admin/login");await page.getByLabel("Username",{exact:true}).fill(config.username);await page.getByLabel("Password",{exact:true}).fill(config.password);await page.getByRole("button",{name:"Sign in",exact:true}).click();await page.waitForURL("**/admin/blog");
  await page.getByRole("button",{name:"New draft",exact:true}).click();
  const slug="qa-complete-"+width+"-"+Date.now();
  await page.getByLabel("Title",{exact:true}).fill("Preparing for a thoughtful primary care visit");
  await page.getByLabel("URL slug",{exact:true}).fill(slug);
  await page.getByLabel("Article HTML",{exact:true}).fill(content);
  await page.getByLabel("Summary",{exact:true}).fill("LOCAL QA FIXTURE: a complete private draft to verify editorial controls and the public article layout.");
  await page.getByText("Search appearance, sources and media",{exact:true}).click();
  await page.getByLabel("SEO title",{exact:true}).fill("Prepare for a primary care visit | Faithful Care");
  await page.getByLabel("SEO description",{exact:true}).fill("A local verification fixture for the Faithful Care editorial workflow, including sources, image review and the protected publication process.");
  await page.getByLabel("Tags (comma separated)",{exact:true}).fill("prevention, visit preparation");
  await page.getByLabel("Medical sources (one URL per line)",{exact:true}).fill(source);
  await page.getByLabel("Medical disclaimer",{exact:true}).fill("LOCAL QA FIXTURE ONLY. General educational information does not replace personal advice from a licensed clinician. In an emergency, call 911.");
  await page.getByRole("button",{name:"Save draft",exact:true}).click();await page.getByRole("status").filter({hasText:"Draft saved"}).waitFor();
  const posts=await (await context.request.get(config.baseUrl+"/api/admin/blog/posts")).json();const p=posts.posts.find(p=>p.slug===slug);assert(p);
  assert.equal((await context.request.get(config.baseUrl+"/blog/"+slug)).status(),404);
  await page.getByLabel("Alternative text",{exact:true}).fill("Solid navy QA image for the layout test");
  await page.getByLabel("Approved image file",{exact:true}).setInputFiles({name:"qa-image.webp",mimeType:"image/webp",buffer:fixture});
  await page.getByRole("button",{name:"Upload candidate",exact:true}).click();
  await page.getByRole("status").filter({hasText:"Candidate uploaded"}).waitFor();
  await page.getByRole("button",{name:"Use reviewed image",exact:true}).click();
  await page.getByRole("status").filter({hasText:"Image selected"}).waitFor();
  await page.getByLabel("Image placement").selectOption("inline");
  await page.getByLabel("After section number",{exact:true}).fill("1");
  await page.getByRole("button",{name:"Upload candidate",exact:true}).click();
  await page.getByRole("status").filter({hasText:"Candidate uploaded"}).waitFor();
  await page.getByRole("button",{name:"Use reviewed image",exact:true}).first().click();await page.getByRole("status").filter({hasText:"Image selected"}).waitFor();
  await page.getByText("Preview the saved article",{exact:true}).click();
  const frame=page.frameLocator('iframe[title="Private article preview"]');await frame.getByRole("heading",{level:1}).waitFor();
  assert.equal(await frame.locator("img").count(),2);
  await page.getByRole("button",{name:"Send to review",exact:true}).click();
  await page.getByLabel("Reviewing clinician",{exact:true}).fill("LOCAL QA FIXTURE, not a clinical approval");
  await page.getByLabel("I confirm the named clinician reviewed this exact saved article.",{exact:true}).check();
  await page.getByRole("button",{name:"Publish reviewed article",exact:true}).click();
  await page.getByRole("status").filter({hasText:"Article published."}).waitFor();
  await page.getByText("Google visibility and publishing checks",{exact:true}).click();
  await page.getByRole("button",{name:"Check Google status",exact:true}).click();await page.getByRole("status").filter({hasText:"Preview remains private"}).waitFor();
  await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:"artifacts/blog/editor-complete-"+width+"x"+height+".png"});
  const publicPage=await context.newPage();publicPage.on("pageerror",e=>errors.push(e.message));publicPage.on("console",m=>{if(m.type()==="error")errors.push(m.text());});
  await publicPage.addInitScript(({key,version})=>localStorage.setItem(key,JSON.stringify({version,state:{necessary:true,analytics:true,advertising:false,personalization:false}})),{key:CONSENT_STORAGE_KEY,version:CONSENT_VERSION});
  const response=await publicPage.goto(config.baseUrl+"/blog/"+slug,{waitUntil:"networkidle"});assert.equal(response.status(),200);
  assert.equal(await publicPage.locator("main h1").count(),1);
  assert.equal(await publicPage.locator("main img").count(),2);
  for(const img of await publicPage.locator("main img").all())await img.scrollIntoViewIfNeeded();await publicPage.waitForFunction(()=>[...document.querySelectorAll("main img")].every(i=>i.complete&&i.naturalWidth>0));await publicPage.evaluate(()=>scrollTo(0,0));
  assert.equal(await publicPage.locator('link[rel="canonical"]').getAttribute("href"),"https://faithfulcaremedical.com/blog/"+slug);
  assert.equal(await publicPage.getByTestId("link-lang-es").getAttribute("href"),"/es/blog");
  const map=await (await context.request.get(config.baseUrl+"/sitemap.xml")).text();assert(map.includes("/blog/"+slug));
  assert.deepEqual(tracking,[],"Health article and editor never load tracking, even with prior consent");
  for(const [w,h] of [[390,844],[1024,768],[1440,900],[1920,1080],[3440,1440]]){await publicPage.setViewportSize({width:w,height:h});assert(await publicPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await publicPage.screenshot({path:"artifacts/blog/article-"+w+"x"+h+".png"});}
  await publicPage.close();
  await page.getByRole("button",{name:"Unpublish",exact:true}).click();await page.getByRole("status").filter({hasText:"Editorial status updated."}).waitFor();
  assert.equal((await context.request.get(config.baseUrl+"/blog/"+slug)).status(),404);
  assert(!(await (await context.request.get(config.baseUrl+"/sitemap.xml")).text()).includes("/blog/"+slug));
  assert.deepEqual(errors,[],"No unexpected browser or console errors");
  await context.close();
 }
 console.log("PASS: real hero/inline upload, review, isolated preview, publication, canonical/sitemap, consent privacy, unpublish and five viewports on desktop/mobile.");
}finally{await browser.close();}
