import assert from "node:assert/strict";
import {test,before,after,beforeEach} from "node:test";
import fs from "node:fs/promises";import {randomUUID} from "node:crypto";import {PGlite} from "@electric-sql/pglite";
process.env.NODE_ENV="test";
const {setTestDatabase,query}=await import("../server/blog/db.ts");
const {createPost,getPost}=await import("../server/blog/posts.ts");
const {blankData}=await import("../server/blog/types.ts");
const {regenerateArticleImage}=await import("../server/blog/regenerate-image.ts");
let db;before(async()=>{db=new PGlite();for(const n of (await fs.readdir("migrations/blog")).filter(n=>n.endsWith(".sql")).sort())await db.exec(await fs.readFile("migrations/blog/"+n,"utf8"));setTestDatabase(db);Object.assign(process.env,{BLOG_IMAGES_ENABLED:"true",BLOB_READ_WRITE_TOKEN:"test-only",BLOG_AI_ENABLED:"true",OPENAI_API_KEY:"test-only",BLOB_PUBLIC_HOSTNAME:"client.public.blob.vercel-storage.com"});});after(async()=>{setTestDatabase();await db.close();});beforeEach(async()=>{await query("DELETE FROM fc_blog_limits");});
async function fixture(){const url="https://client.public.blob.vercel-storage.com/faithful-care/blog/"+randomUUID()+".webp";const post=await createPost({title:"Preparing care questions",slug:"test-"+randomUUID(),language:"en",content:"<h2>Preparing a visit</h2><p>Useful questions.</p>",data:{...blankData,hero:url,heroAlt:"Two adults talking"}},"test");const [media]=await query("INSERT INTO fc_blog_media(post_id,url,role,alt,placement,source) VALUES($1,$2,'hero','Two adults talking',1,'ai') RETURNING *",[post.id,url]);return{post,media};}
function services(calls,hook=async()=>{}){return{generateJson:async(instruction,data,images)=>{calls.push({instruction,data,images});return images.length?{alt:"Two adults speaking beside a window"}:{prompt:"Two fictional adults talking beside a window with directional daylight and subtle warm practical light."};},generateImage:async(id,key,role,alt,placement,actor,prompt)=>{calls.push({id,key,prompt});await hook();const [media]=await query("INSERT INTO fc_blog_media(post_id,url,role,alt,placement,source) VALUES($1,$2,$3,$4,$5,'ai') RETURNING *",[id,"https://client.public.blob.vercel-storage.com/faithful-care/blog/"+randomUUID()+".webp",role,alt,placement]);return media;}};}
test("short adjustment becomes branded prompt and one replacement; old media and sibling remain",async()=>{const{post,media}=await fixture(),calls=[];const sibling=await createPost({title:"Preparar consulta",slug:"es-"+randomUUID(),language:"es",content:post.content,data:{...post.data,heroAlt:"Dos adultos conversando"}},"test",post.translation_group);const input={requestId:randomUUID(),mediaId:media.id,version:post.version,adjustment:"Luz mÃƒÆ’Ã‚Â¡s natural"};const result=await regenerateArticleImage(post.id,input,"test",services(calls));assert.equal(calls[0].data.adjustment,input.adjustment);assert.deepEqual(calls[0].images,[]);assert.match(calls[0].instruction,/Faithful Care/);assert.equal(calls[2].images[0],result.media.url);assert.equal(result.post.data.hero,result.media.url);assert.equal(result.post.data.heroAlt,"Two adults speaking beside a window");assert.equal((await getPost(sibling.id)).data.hero,media.url);assert.equal((await query("SELECT id FROM fc_blog_media WHERE post_id=$1",[post.id])).length,2);await assert.rejects(()=>regenerateArticleImage(post.id,input,"test",services([])),e=>e.status===409);});
test("concurrent edit preserves old image and stores candidate without overwriting",async()=>{const{post,media}=await fixture();await assert.rejects(()=>regenerateArticleImage(post.id,{requestId:randomUUID(),mediaId:media.id,version:post.version},"test",services([],async()=>{await query("UPDATE fc_blog_posts SET version=version+1 WHERE id=$1",[post.id]);})),e=>e.status===409);assert.equal((await getPost(post.id)).data.hero,media.url);});
test("published or foreign images are rejected before providers",async()=>{const a=await fixture(),b=await fixture(),calls=[];await assert.rejects(()=>regenerateArticleImage(a.post.id,{requestId:randomUUID(),mediaId:b.media.id,version:a.post.version},"test",services(calls)),e=>e.status===400);await query("UPDATE fc_blog_posts SET status='published',published_at=now() WHERE id=$1",[a.post.id]);await assert.rejects(()=>regenerateArticleImage(a.post.id,{requestId:randomUUID(),mediaId:a.media.id,version:a.post.version},"test",services(calls)),e=>e.status===409);assert.equal(calls.length,0);});

test("disabled images fail before reserving credits or calling the planner",async()=>{const{post,media}=await fixture(),calls=[];process.env.BLOG_IMAGES_ENABLED="false";try{await assert.rejects(()=>regenerateArticleImage(post.id,{requestId:randomUUID(),mediaId:media.id,version:post.version},"test",services(calls)),e=>e.status===503);assert.equal(calls.length,0);assert.equal((await query("SELECT * FROM fc_blog_limits")).length,0);}finally{process.env.BLOG_IMAGES_ENABLED="true";}});

test("identifiers anywhere in the planner context stop before external calls and credit reservation",async()=>{for(const field of ["title","section","alt","prompt"]){const{post,media}=await fixture(),calls=[];if(field==="title")await query("UPDATE fc_blog_posts SET title='Contact example@example.test' WHERE id=$1",[post.id]);if(field==="section")await query("UPDATE fc_blog_posts SET content='<h2>Visit</h2><p>DOB: 1950-01-01</p>' WHERE id=$1",[post.id]);if(field==="alt")await query("UPDATE fc_blog_media SET alt='MRN: example' WHERE id=$1",[media.id]);if(field==="prompt")await query("UPDATE fc_blog_media SET prompt='Account 123-45-6789' WHERE id=$1",[media.id]);await assert.rejects(()=>regenerateArticleImage(post.id,{requestId:randomUUID(),mediaId:media.id,version:post.version,adjustment:"Softer daylight"},"test",services(calls)),e=>e.status===400);assert.equal(calls.length,0);assert.equal((await query("SELECT * FROM fc_blog_limits")).length,0);}});
