import assert from "node:assert/strict";import {afterEach,test} from "node:test";import {ownedMediaUrl} from "../server/blog/media-url.ts";import {mediaConfigured} from "../server/blog/media.ts";
const authKeys=["VERCEL_OIDC_TOKEN","BLOB_STORE_ID","BLOB_READ_WRITE_TOKEN","BLOB_PUBLIC_HOSTNAME"];
const originalAuth=Object.fromEntries(authKeys.map(key=>[key,process.env[key]]));
afterEach(()=>{for(const key of authKeys){const value=originalAuth[key];if(value===undefined)delete process.env[key];else process.env[key]=value;}});
test("media URLs must belong to this client's exact public store and image path",()=>{process.env.BLOB_PUBLIC_HOSTNAME="client.public.blob.vercel-storage.com";assert(ownedMediaUrl("https://client.public.blob.vercel-storage.com/faithful-care/blog/a.webp"));for(const url of ["https://other.public.blob.vercel-storage.com/faithful-care/blog/a.webp","https://client.public.blob.vercel-storage.com.evil.test/faithful-care/blog/a.webp","https://client.public.blob.vercel-storage.com/other/a.webp","https://client.public.blob.vercel-storage.com/faithful-care/blog/a.svg","https://user@client.public.blob.vercel-storage.com/faithful-care/blog/a.webp","https://client.public.blob.vercel-storage.com/faithful-care/blog/a.webp?x=1","javascript:alert(1)"])assert.equal(ownedMediaUrl(url),false,url);delete process.env.BLOB_PUBLIC_HOSTNAME;});
test("Vercel OIDC configures media from its persistent store connection",()=>{delete process.env.BLOB_READ_WRITE_TOKEN;delete process.env.VERCEL_OIDC_TOKEN;process.env.BLOB_PUBLIC_HOSTNAME="client.public.blob.vercel-storage.com";delete process.env.BLOB_STORE_ID;assert.equal(mediaConfigured(),false);process.env.BLOB_STORE_ID="store_unit_only";assert.equal(mediaConfigured(),true);});
test("the legacy Blob token remains a local transition fallback",()=>{delete process.env.VERCEL_OIDC_TOKEN;delete process.env.BLOB_STORE_ID;process.env.BLOB_READ_WRITE_TOKEN="unit-only-legacy";process.env.BLOB_PUBLIC_HOSTNAME="client.public.blob.vercel-storage.com";assert.equal(mediaConfigured(),true);});
test("OIDC remains preferred-ready while a legacy fallback coexists",()=>{process.env.VERCEL_OIDC_TOKEN="unit-only-oidc";process.env.BLOB_STORE_ID="store_unit_only";process.env.BLOB_READ_WRITE_TOKEN="unit-only-legacy";process.env.BLOB_PUBLIC_HOSTNAME="client.public.blob.vercel-storage.com";assert.equal(mediaConfigured(),true);});
test("media stays disabled without an exact store hostname or authentication",()=>{delete process.env.BLOB_PUBLIC_HOSTNAME;delete process.env.BLOB_READ_WRITE_TOKEN;delete process.env.VERCEL_OIDC_TOKEN;delete process.env.BLOB_STORE_ID;assert.equal(mediaConfigured(),false);process.env.BLOB_STORE_ID="store_unit_only";assert.equal(mediaConfigured(),false);});
