import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {chromium} from 'playwright';
const auth=JSON.parse(await fs.readFile(process.env.IMAGE_UI_AUTH_FILE||'.local/blog-e2e.json','utf8'));
if(process.env.IMAGE_UI_BASE_URL)auth.baseUrl=process.env.IMAGE_UI_BASE_URL;
let protection=[];if(process.env.IMAGE_UI_COOKIE_FILE){const jar=await fs.readFile(process.env.IMAGE_UI_COOKIE_FILE,'utf8');protection=jar.split(/\r?\n/).map(l=>l.replace(/^#HttpOnly_/, '')).filter(l=>l&&!l.startsWith('#')).map(l=>{const [domain,,path,secure,expires,name,value]=l.split('\t');return{domain,path,secure:secure==='TRUE',expires:Number(expires)||-1,name,value};});}
const browser=await chromium.launch();await fs.mkdir('artifacts/blog-regenerate',{recursive:true});let session;
try{for(const [width,height] of [[390,844],[1024,768],[1440,900],[1920,1080],[3440,1440]]){
 const context=await browser.newContext({viewport:{width,height},storageState:session}),page=await context.newPage(),errors=[];if(protection.length)await context.addCookies(protection);if(process.env.EXPECTED_SHA)assert.equal((await(await context.request.get(auth.baseUrl+'/api/blog/deployment')).json()).sha,process.env.EXPECTED_SHA);
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 const original='/__fixture-original.svg',replacement='/icon.png';let requests=[];
 let media=[{id:'11111111-1111-4111-8111-111111111111',role:'hero',url:original,alt:'Original editorial illustration',placement:1,source:'ai',reviewed:false}];
 let post={id:'22222222-2222-4222-8222-222222222222',version:2,translation_group:'fixture',language:'en',title:'Image replacement fixture',slug:'image-replacement-fixture',status:'draft',updated_at:new Date().toISOString(),content:'<h2>Preparing a visit</h2><p>Useful questions.</p>',data:{excerpt:'Private browser fixture',metaTitle:'Fixture',metaDescription:'Fixture',category:'primary-care',tags:[],author:'Editorial team',hero:original,heroAlt:media[0].alt,images:[],sources:[],topic:'',disclaimer:''}};
 await page.route('**/__fixture-original.svg',route=>route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="800" height="500"><rect width="800" height="500" fill="#dbe9ef"/></svg>'}));
 await page.route('**/icon.png',route=>route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="800" height="500"><rect width="800" height="500" fill="#d1efed"/></svg>'}));
 await page.route('**/api/admin/blog/posts',route=>route.fulfill({json:{posts:[post]}}));
 await page.route('**/api/admin/blog/posts/'+post.id+'/**',async route=>{const path=new URL(route.request().url()).pathname;if(path.endsWith('/preview'))return route.fulfill({json:{html:'<h1>Image replacement fixture</h1><img src="'+post.data.hero+'" alt="'+post.data.heroAlt+'">'}});if(path.endsWith('/media/regenerate')){requests.push(route.request().postDataJSON());await new Promise(r=>setTimeout(r,1200));const item={...media[0],id:'33333333-3333-4333-8333-333333333333',url:replacement,alt:'New editorial illustration'};media=[item,...media];post={...post,version:post.version+1,data:{...post.data,hero:replacement,heroAlt:item.alt}};return route.fulfill({json:{post,media:item}});}if(path.endsWith('/media'))return route.fulfill({json:{media}});throw Error('Unexpected fixture request '+path);});
 if(!session){await page.goto(auth.baseUrl+'/admin/login');await page.getByLabel('Username',{exact:true}).fill(auth.username);await page.getByLabel('Password',{exact:true}).fill(auth.password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL('**/admin/blog');session=await context.storageState();}else await page.goto(auth.baseUrl+'/admin/blog');
 await page.getByRole('button',{name:'Preview',exact:true}).click();await page.getByRole('button',{name:'Change or regenerate an image',exact:true}).click();assert.equal(await page.getByText('Visual review needed',{exact:true}).count(),0);
 await page.waitForFunction(()=>[...document.querySelectorAll('.media-candidate img')].every(i=>i.complete&&i.naturalWidth>0));await page.getByRole('button',{name:'Regenerate image',exact:true}).click();await page.getByLabel('What would you change? (optional)').fill('Luz más natural');await page.getByRole('button',{name:'Cancel',exact:true}).click();assert.equal(requests.length,0);
 await page.getByRole('button',{name:'Regenerate image',exact:true}).click();await page.getByLabel('What would you change? (optional)').fill(width===390?'':'Luz más natural');await page.getByLabel('What would you change? (optional)').scrollIntoViewIfNeeded();await page.screenshot({path:`artifacts/blog-regenerate/adjustment-${width}x${height}.png`});
 await page.getByRole('button',{name:'Generate replacement',exact:true}).click();await page.getByText('Preparing the image. This may take a few minutes.',{exact:true}).waitFor();assert(await page.getByRole('button',{name:'Edit text',exact:true}).isDisabled());assert(await page.getByRole('button',{name:'Back to dashboard',exact:true}).isDisabled());await page.getByRole('status').filter({hasText:'New image saved in this article.'}).waitFor();assert.equal(requests.length,1);assert.equal(requests[0].adjustment,width===390?'':'Luz más natural');assert.equal(requests[0].version,2);assert.equal(await page.locator('.media-candidate').count(),2);
 await page.getByRole('button',{name:'Preview',exact:true}).click();const preview=page.getByRole('region',{name:'Saved article preview'});await preview.getByAltText('New editorial illustration').waitFor();assert.equal(await preview.getByAltText('New editorial illustration').getAttribute('src'),replacement);assert(await page.locator('body').evaluate(el=>el.scrollWidth<=innerWidth+1));assert.deepEqual(errors,[]);await context.close();}
 console.log('PASS: preview to regenerate, optional short adjustment, cancel, loading, automatic replacement and updated preview, preserved old image, five viewports; provider simulated.');
}finally{await browser.close();}
