import assert from "node:assert/strict";
import {test,before,after} from "node:test";
import fs from "node:fs/promises";
import {PGlite} from "@electric-sql/pglite";
process.env.NODE_ENV="test";
const {setTestDatabase,query}=await import("../server/blog/db.ts");
const {passwordHash,login,session,logout,assertOrigin,consumeLimit}=await import("../server/blog/auth.ts");
const {createPost,editPost,getPost,listPosts,transition,publicPost}=await import("../server/blog/posts.ts");
const {blankData}=await import("../server/blog/types.ts");
const {sanitize}=await import("../server/blog/content.ts");
let db;
before(async()=>{db=new PGlite();for(const name of (await fs.readdir(new URL("../migrations/blog/",import.meta.url))).filter(n=>n.endsWith(".sql")).sort())await db.exec(await fs.readFile(new URL("../migrations/blog/"+name,import.meta.url),"utf8"));setTestDatabase(db);process.env.BLOG_ADMIN_USERNAME="test-editor";process.env.BLOG_ADMIN_PASSWORD_HASH=passwordHash("unit-only-example");process.env.BLOG_ADMIN_SESSION_SECRET="unit-only-secret-1234567890123456789012345";});
after(async()=>{setTestDatabase();await db.close();});
const input=(slug)=>({language:"en",title:"Preparing for your visit",slug,content:"<h2>Preparing</h2><p>Bring your questions.</p>",data:{...blankData}});
test("credentials, revocation, rotation, CSRF and durable rate limits",async()=>{
 await assert.rejects(()=>login("test-editor","wrong","wrong-test"),e=>e.status===401);
 const token=await login("test-editor","unit-only-example","valid-test");
 assert.equal((await session(token)).username,"test-editor");
 assert.equal(await session(token+"bad"),null);
 const rows=await query("SELECT token_hash FROM fc_blog_sessions");
 assert.notEqual(rows[0].token_hash,token);
 await logout(token);assert.equal(await session(token),null);
 const token2=await login("test-editor","unit-only-example","rotation");
 process.env.BLOG_ADMIN_SESSION_SECRET+="rotated";assert.equal(await session(token2),null);
 assert.throws(()=>assertOrigin(new Request("https://site.test/api",{headers:{origin:"https://attacker.test"}})),e=>e.status===403);
 assert.throws(()=>assertOrigin(new Request("https://site.test/api")),e=>e.status===403);
 assertOrigin(new Request("https://site.test/api",{headers:{origin:"https://site.test"}}));
 for(let i=0;i<3;i++)await consumeLimit("bounded-test",3,900);
 await assert.rejects(()=>consumeLimit("bounded-test",3,900),e=>e.status===429);
});
test("private drafts, sanitization, stale edits and publication gates",async()=>{
 const p=await createPost({...input("private-test"),content:'<h2>Safe</h2><script>alert(1)</script><p onclick="alert(1)">Text <a href="javascript:alert(1)">x</a></p>'},"tester");
 assert(!p.content.includes("<script"));assert(!p.content.includes("onclick"));assert(!p.content.includes("javascript:"));
 assert.equal(await publicPost("en",p.slug),null);
 assert.equal((await listPosts()).length,0);
 await assert.rejects(()=>transition(p.id,"published",p.version,"tester","Dr. Test"),e=>e.status===409);
 const edited=await editPost(p.id,input("private-test"),p.version,"tester");
 await assert.rejects(()=>editPost(p.id,input("stale-test"),p.version,"tester"),e=>e.status===409);
 const review=await transition(p.id,"pending_review",edited.version,"tester");
 await assert.rejects(()=>transition(p.id,"published",review.version,"tester","Dr. Test"),e=>e.status===422);
 assert.equal((await getPost(p.id)).status,"pending_review");
});
test("reviewed publish, language isolation and unpublish",async()=>{
 const source="https://medlineplus.gov/healthscreening.html";
 await query("INSERT INTO fc_blog_links(url,kind,publisher,score,reason,approved,health,checked_at) VALUES($1,'external','MedlinePlus',95,'US National Library of Medicine',true,'healthy',now())",[source]);
 const body="<h2>Prepare for the appointment</h2>"+Array.from({length:85},()=>"<p>Bring a written list of your questions and current medicines to discuss with your clinician.</p>").join("")+'<p><a href="/primary-care">Primary care</a> <a href="/contact">Contact</a> <a href="'+source+'">MedlinePlus</a></p>';
 const p=await createPost({...input("reviewed-test"),content:body,data:{...blankData,excerpt:"Practical questions to help prepare for an upcoming primary care visit.",metaTitle:"Preparing for a primary care visit",metaDescription:"Prepare for a primary care visit with a question list, your current medicines and practical information to discuss with your clinician.",tags:["prevention"],sources:[source],disclaimer:"This article provides general educational information and does not replace personal advice from a licensed clinician. In an emergency call 911."}},"tester");
 const review=await transition(p.id,"pending_review",p.version,"tester");
 const published=await transition(p.id,"published",review.version,"tester","Test clinician");
 assert.equal((await publicPost("en",p.slug)).id,p.id);assert.equal(await publicPost("es",p.slug),null);
 await assert.rejects(()=>editPost(p.id,input(p.slug),published.version,"tester"),e=>e.status===409);
 const unpublished=await transition(p.id,"draft",published.version,"tester");
 assert.equal(unpublished.published_at,null);assert.equal(await publicPost("en",p.slug),null);
});
test("sanitization is idempotent and rejects encoded active content",()=>{
 const clean=sanitize('<p><a href="https://medlineplus.gov/">Reference</a><a href="/contact">Care</a><img src=x onerror=alert(1)></p>');
 assert.equal(sanitize(clean),clean);
 assert(!sanitize('<a href="&#106;avascript:alert(1)">bad</a>').includes("javascript"));
});

test("generation operation IDs cannot duplicate drafts and saving completes atomically",async()=>{
 const {claimJob,saveGeneratedPost}=await import("../server/blog/jobs.ts");
 const key="2bb3a3a9-a2e6-4e2c-9c1a-89349079018d";
 const job=await claimJob("generate",key,"tester",{topicId:"visit-preparation"});
 await assert.rejects(()=>claimJob("generate",key,"tester"),e=>e.status===409);
 const p=await saveGeneratedPost(input("generated-atomic"),"tester",job.id);
 const [saved]=await query("SELECT * FROM fc_blog_jobs WHERE id=$1",[job.id]);
 assert.equal(saved.status,"completed");assert.equal(saved.post_id,p.id);
 assert.equal(p.status,"draft");assert.equal(p.published_at,null);
 await assert.rejects(()=>saveGeneratedPost(input("generated-repeat"),"tester",job.id),e=>e.status===409);
});
