import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {chromium} from 'playwright';
import {AUTO_STEPS} from '../shared/blog-auto.ts';
const auth=JSON.parse(await fs.readFile('.local/blog-e2e.json','utf8'));const browser=await chromium.launch();await fs.mkdir('artifacts/blog-progress',{recursive:true});
let session;
try{for(const [width,height] of [[390,844],[1024,768],[1440,900],[1920,1080],[3440,1440]]){
const context=await browser.newContext({viewport:{width,height},reducedMotion:'reduce',storageState:session}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
let run={id:'progress-ui-fixture',requestId:'progress-ui-request',status:'running',cursor:9,busy:true,language:'en',postId:null,translationId:null,error:null,steps:AUTO_STEPS.map(([id,label],i)=>({id,label,status:i<9?'completed':i===9?'running':'pending',detail:i<9?'Fixture output retained. '.repeat(12):i===9?'Generating image.':''}))};
// UI contract only. No real provider requests or generated content.
await page.route('**/api/admin/blog/auto/**',async route=>{const path=new URL(route.request().url()).pathname;if(path.endsWith('/advance'))throw Error('Busy fixture must not advance');if(path.endsWith('/events'))return route.fulfill({status:200,contentType:'text/event-stream',body:'data: '+JSON.stringify({run})+'\n\n'});await route.fulfill({json:path.endsWith('/config')?{ready:true,missing:[]}:{run}});});
if(!session){await page.goto(auth.baseUrl+'/admin/login');await page.getByLabel('Username',{exact:true}).fill(auth.username);await page.getByLabel('Password',{exact:true}).fill(auth.password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL('**/admin/blog');session=await context.storageState();}else await page.goto(auth.baseUrl+'/admin/blog');await page.getByRole('button',{name:/Auto Generate|View generation progress/}).click();
const progress=page.getByRole('progressbar',{name:'Overall article preparation'});await progress.waitFor();assert.equal(await progress.getAttribute('value'),'9');assert.equal(await progress.getAttribute('max'),'15');await page.getByRole('status').filter({hasText:'Step 10 of 15: Generate hero image'}).waitFor();assert.equal(await page.locator('.auto-progress .auto-spinner').count(),1);assert.equal(await page.locator('#auto-step-hero .auto-spinner').count(),1);
await page.getByRole('button',{name:'Show current step',exact:true}).click();const dialog=page.getByRole('dialog');await page.waitForFunction(()=>document.querySelector('.editor-dialog').scrollTop>200);const top=await dialog.boundingBox(),banner=await page.locator('.auto-progress').boundingBox();assert(banner.y>=top.y&&banner.y+banner.height<top.y+top.height);assert((await page.locator('#auto-step-hero').boundingBox()).y>=banner.y+banner.height-2);await page.screenshot({path:`artifacts/blog-progress/running-${width}x${height}.png`});assert.equal(await page.locator('.auto-spinner').first().evaluate(el=>getComputedStyle(el).animationName),'none');await page.emulateMedia({reducedMotion:'no-preference'});assert.equal(await page.locator('.auto-spinner').first().evaluate(el=>getComputedStyle(el).animationName),'auto-progress-spin');await page.emulateMedia({reducedMotion:'reduce'});assert(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth+1));
run={...run,status:'failed',busy:false,error:'Fixture image provider failed.',steps:run.steps.map((s,i)=>i===9?{...s,status:'failed'}:s)};await page.getByRole('status').filter({hasText:'Generation needs attention'}).waitFor({timeout:10000});assert.equal(await page.locator('.auto-spinner').count(),0);assert.equal(await progress.getAttribute('value'),'9');
run={...run,status:'completed',error:null,cursor:15,steps:run.steps.map((s,i)=>({...s,status:i===13?'skipped':'completed'}))};await page.reload();await page.getByRole('button',{name:/Auto Generate|View generation progress/}).click();await page.getByRole('status').filter({hasText:'Draft ready to review'}).waitFor();assert.equal(await progress.getAttribute('value'),'15');assert.equal(await page.locator('.auto-spinner').count(),0);assert.deepEqual(errors,[]);await context.close();}
console.log('PASS: progress values, active step, sticky summary, jump action, failed/completed/skipped states, reduced motion, no errors, five viewports; providers simulated.');}finally{await browser.close();}
