import {createHash} from "node:crypto";

// Shared by the planner and the final image request, including manual generations.
export const imageScenePolicy = "Faithful Care serves Naples, Collier County, Southwest Florida, USA. Naples always means Naples, Florida, never Naples, Italy or Napoli. Settings may include a modest contemporary interior, a studio-style room, or a shaded low-rise subtropical courtyard. Any exterior detail must be geographically generic and consistent with flat Southwest Florida. No recognizable landmarks, cityscapes, volcanoes, mountains or Italian scenery. This is a generic editorial illustration, not a photograph of the actual Faithful Care clinic or its staff. People are fictional adults only, never real patients, named clinicians or testimonials. No imitation of Dr. Addys Reve or other real people, medical procedures, visible medical records, readable text, logos or dramatic illness. Preserve ordinary individual faces, natural skin texture and coherent anatomy; no beauty-filter smoothing, waxy skin, cloned faces or mannequin expressions. These location, identity and realism requirements override any conflicting article title, section context or suggested image prompt.";

export const editorialPhotography = "Create exactly ONE standalone landscape photograph for an educational primary and palliative care blog. Photorealistic, honest and unposed editorial photography; restrained navy, soft teal and warm neutral accents. COMPOSITION: eye-level environmental or medium framing, full-frame camera with one 50mm lens, depth of field appropriate to the assigned subject; only when two people are assigned, keep both participants' eyes readable; breathing room and coherent room details, important faces and hands inside the crop. LIGHTING: follow the single spatial lighting setup assigned to this scene. Establish the position of the main source, the weaker fill and any practical background light, with believable distance falloff and light blocked by bodies or furniture. When people are present, keep the shadow-side eye readable while cheeks and neck retain depth; otherwise express depth through the assigned objects and room. SKIN: natural skin texture at normal viewing size, fine facial hair, slight tonal variation and age-appropriate creases. Skin is predominantly diffuse with small, subdued highlights only where the source can reflect; forehead, cheeks and nose retain detail instead of broad polished shine. FINISH: restrained professional RAW-style development, neutral skin white balance, gentle highlight roll-off, modest local contrast and subtle fine grain. Preserve pores and expression lines; background and skin may have different exposure and color temperature. Keep two or three meaningful everyday elements, cotton or linen clothing with real folds and contact shadows. Create an entirely new image from text, never edit or reuse a previous generated image.";

// Appended after model-written scene text so a generic stock-photo direction cannot
// replace the lighting, attention and surface rules on either image-generation path.
export const humanRealismRequirements = "PHOTOGRAPHIC REALISM REQUIREMENTS: For a human interaction, specify who is on the left and right, who is speaking and listening, and one concrete gaze target for each person. Head turns, both pupils and body orientation must agree with that target. In mutual conversation each person looks at the other person's eyes, not past their shoulder or at the camera. In a shared-object action both look at the same visible point on that object instead of pretending to make eye contact. A solitary person attends to a named visible object or a clearly located conversation partner outside the crop. Catchlights reflect the same physical light sources with position and visibility appropriate to each head angle; do not paste identical eye highlights onto different orientations. Use directional ambient light with controlled fill and natural falloff, not uniform frontal face illumination. Any warm lamp contributes locally to nearby furniture or background while the window remains the dominant cooler source; do not tint the entire scene orange. Render natural skin texture and subdued, source-shaped skin highlights; avoid waxy gradients, oily forehead glare, wet-looking cheeks, smoothing, beauty retouching, artificial pore overlays, sharpened halos and lifted HDR shadows. Subtle professional finishing means restrained color and highlight control, never reshaping faces or removing their texture. These requirements take precedence over conflicting scene wording; do not add people to an assigned people-free environment or detail.";

export type EditorialScene={family:"people"|"environment"|"detail";direction:string};
export function articleSceneMix(seed:string):EditorialScene[]{
 const digest=createHash("sha256").update(seed).digest();
 const casts=[
  "one fictional adult in their late 60s, medium-brown skin, short grey curls, a broad build and expressive smile lines",
  "two fictional adults, one in their early 40s with deep-brown skin and natural coils, the other in their late 60s with light olive skin and silver hair; distinct faces and builds",
  "one fictional adult in their mid 50s, warm olive skin, a stocky build, short salt-and-pepper hair and slight facial asymmetry",
  "one fictional adult in their early 40s, fair freckled skin, wavy dark hair and thin-frame glasses",
 ];
 const settings=[
  "a modest contemporary room with upholstered chairs and matte oak furniture; a large side window camera-left supplies soft 5200K daylight at roughly 45 degrees, a weak neutral wall bounce leaves the far side of the seating area visibly darker, and a shaded 2800K table lamp at the rear lights only the adjacent wall and furniture; the room falls away in depth",
  "a minimal furnished studio-style room with a cream wall and upholstered seating; one large diffused 5000K key camera-left above the seating area creates soft diagonal shadows, negative fill camera-right shapes the furnishings, and a weak flagged rear accent grazes the edge of the upholstered seating; the wall is a little darker than the foreground",
  "a shaded subtropical courtyard with low-rise stucco walls and local greenery; broad cool sky light enters from the open camera-left side, warm pale stucco provides weak reflected fill on the opposite side, and the roof edge and plants cast plausible soft occlusion shadows; the background retains daylight detail",
 ];
 const castIndex=digest[1]%casts.length;
 const attention=castIndex===1
  ? digest[3]%2===0
   ? "Place the younger adult on camera-left, turned toward the older adult on camera-right. The older adult is speaking softly and looking at the younger adult's eyes; the younger adult listens and looks back at the speaker's eyes. Their pupils converge on those respective faces, with relaxed shoulder turns toward each other."
   : "Place the younger adult on camera-left and the older adult on camera-right. They share attention on the same visible point on an open blank notebook between them; both heads and both pairs of pupils angle down toward that point. The older adult on camera-right speaks quietly and rests a hand beside the page; the younger adult on camera-left listens with hands resting on their lap. Both continue looking at that shared point rather than at the camera."
  : "The solo adult performs the section-specific action described in the scene brief. Preserve its meaningful prop or activity and name one exact visible attention target within it. Head and both eyes angle toward the same concrete target; hands participate naturally in that action. If the brief has no object or activity, show quiet reflection toward one particular leaf on a visible plant beside the chair. Do not replace an article-specific activity with a generic notebook pose. Keep exactly one person.";
 const scenes:EditorialScene[]=[
  {family:"people",direction:`HUMAN SCENE: Include ${casts[castIndex]} in ${settings[digest[2]%settings.length]}. ${attention} Keep this attention map and lighting setup when adapting props to the article section. Ordinary cotton or linen clothing with real folds; spontaneous restrained expression, not a posed healthcare campaign. Keep people the subject, not a desk accessory. This is an illustrative scene, not a care encounter at the actual practice.`},
  {family:"environment",direction:`ENVIRONMENT SCENE: Show an unoccupied ${settings[(digest[2]+1)%settings.length]}. Use a wider environmental composition with useful spatial context and two or three meaningful furnishings. Choose a different setting and light scheme from the human image. Do not make a tabletop close-up the subject.`},
  {family:"detail",direction:"CONTEXTUAL DETAIL: Create a people-free detail tied to the chosen article section, with natural side light, tactile material and visible contact shadows. Select a subject that adds information rather than repeating generic mugs, pens, phones or notebooks. Its subject, distance and angle must differ from the other two images."},
 ];
 const rotation=digest[0]%scenes.length;
 return scenes.map((_,index)=>scenes[(index+rotation)%scenes.length]);
}
export function withImageScenePolicy(context:string){
 return context+"\n\n"+humanRealismRequirements+"\n\nMandatory location, identity and realism requirements: "+imageScenePolicy;
}
