import {verifiedBlogAuthor} from "../../shared/blog-author";
import {decodeHTML} from "entities";
import {sanitize,plain} from "./content";
import {ownedMediaUrl} from "./media-url";
import type {Post} from "./types";
export const escapeHtml=(s:string)=>s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
export function articleHeadings(post:Post){return [...sanitize(post.content).matchAll(/<h2\b[^>]*>([\s\S]*?)<\/h2>/gi)].map((m,i)=>({id:"article-section-"+(i+1),title:decodeHTML(plain(m[1]))}));}
export function articleHtml(post:Post){
 const sections=sanitize(post.content).split(/(?=<h2\b)/i);
 let heading=0;
 return sections.map(section=>{
  if(/^<h2\b/i.test(section)){heading++;section=section.replace(/<h2\b[^>]*>/i,'<h2 id="article-section-'+heading+'">');}
  const media=post.data.images.filter(i=>i.afterHeading===heading&&ownedMediaUrl(i.url));
  section=section.replace(/<table\b[^>]*>[\s\S]*?<\/table>/gi,table=>'<div class="article-table-scroll" tabindex="0" role="region" aria-label="'+(post.language==="es"?"Tabla del artículo":"Article table")+'">'+table+'</div>');
  return section+media.map(i=>'<figure><img src="'+escapeHtml(i.url)+'" alt="'+escapeHtml(i.alt)+'" loading="lazy"/></figure>').join("");
 }).join("");
}
export function previewArticle(post:Post){
 const es=post.language==="es",headings=articleHeadings(post),words=plain(post.content).split(/\s+/).filter(Boolean).length;
 const category=es?({"prevention":"Prevención","primary-care":"Atención primaria","chronic-care":"Enfermedades crónicas","senior-care":"Adultos mayores","palliative-care":"Cuidados paliativos","family-support":"Apoyo familiar"}[post.data.category]||post.data.category):post.data.category.replaceAll("-"," ");
 const author=verifiedBlogAuthor(post.data.author);
 const byline=author?'<a class="blog-author" rel="author" href="'+author.biography+'"><span class="blog-author-avatar"><img src="'+author.image+'" alt="" width="56" height="56"/></span><span><small>'+(es?'Por':'By')+'</small><strong>'+author.name+'</strong><span class="blog-author-bio">'+(es?'Conoce a la doctora':'Meet your doctor')+' →</span></span></a>':'<span>'+escapeHtml(post.data.author)+'</span>';
 const outline=headings.map(h=>'<li><a href="#'+h.id+'">'+escapeHtml(h.title)+'</a></li>').join("");
 return '<article lang="'+post.language+'" class="saved-article-preview"><header><p class="eyebrow">'+escapeHtml(category)+' · '+post.language.toUpperCase()+'</p><h1>'+escapeHtml(post.title)+'</h1><p class="intro">'+escapeHtml(post.data.excerpt)+'</p><div class="meta blog-meta">'+byline+'<span>'+Math.max(1,Math.ceil(words/200))+(es?' min de lectura':' min read')+'</span></div></header>'+(ownedMediaUrl(post.data.hero)?'<img class="hero" src="'+escapeHtml(post.data.hero)+'" alt="'+escapeHtml(post.data.heroAlt)+'"/>':'')+'<div class="reading-layout"><nav aria-label="'+(es?'Índice del artículo':'Article contents')+'"><details open><summary>'+(es?'En este artículo':'In this article')+'</summary><ol>'+outline+'</ol></details></nav><div><div class="blog-copy">'+articleHtml(post)+'</div><aside>'+escapeHtml(post.data.disclaimer)+'</aside><section class="sources"><h2>'+(es?'Fuentes':'Sources')+'</h2><ul>'+post.data.sources.map(url=>'<li>'+escapeHtml(url)+'</li>').join("")+'</ul></section></div></div></article>';
}
export function previewHtml(post:Post){return '<!doctype html><html lang="'+post.language+'"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Private article preview</title><style>'+previewStyles+'</style><body>'+previewArticle(post)+'</body></html>';}
const previewStyles=`.blog-author{display:inline-flex;align-items:center;gap:12px;color:#092945;text-decoration:none;line-height:1.4}.blog-author>span:last-child{display:flex;flex-direction:column;gap:3px}.blog-author small{font-size:12px;color:#526675}.blog-author strong{font-size:15px;font-weight:600}.blog-author-bio{font-size:12px;color:#0067cc;text-decoration:underline}.blog-author-avatar{display:block;width:56px;height:56px;flex:0 0 56px;border-radius:50%;overflow:hidden;background:#edf6f8}.blog-author .blog-author-avatar img{display:block;width:56px;height:56px;margin:0;border-radius:0;object-fit:cover;transform:scale(2.2);transform-origin:50% 0}.blog-meta{display:flex;gap:18px;flex-wrap:wrap;align-items:center}.blog-author:focus-visible{outline:3px solid #00a4ae;outline-offset:4px;border-radius:5px}*{box-sizing:border-box}html{scroll-behavior:smooth}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}body{margin:0;color:#092945;background:white;font:17px/1.85 system-ui,sans-serif}article{max-width:1200px;margin:0 auto;padding:40px 36px 70px}header{max-width:900px}.eyebrow{font-size:11px;letter-spacing:.14em;text-transform:uppercase;color:#006ba6;font-weight:600}h1{font:clamp(32px,4.5vw,58px)/1.12 Georgia,serif;margin:20px 0}.intro{font-size:21px;line-height:1.65;color:#526675}.meta{font-size:13px;color:#526675}img{display:block;width:100%;height:auto;border-radius:16px}.hero{aspect-ratio:16/9;object-fit:cover;margin:32px 0}.reading-layout{display:grid;grid-template-columns:190px minmax(0,1fr);gap:40px;align-items:start}.reading-layout>div{min-width:0}nav{position:sticky;top:24px;max-height:calc(100vh - 50px);overflow:auto;font-size:12px;padding-top:26px}nav summary{font-weight:600;cursor:pointer}nav ol{list-style:none;padding:0;border-left:1px solid #dce6ed}nav a{display:block;padding:9px 14px;color:#526675;text-decoration:none;line-height:1.6}nav a:hover{background:#edf6fc;color:#0067cc}h2{font:30px/1.25 Georgia,serif;margin:36px 0 18px;scroll-margin-top:24px}h3{font-size:21px;line-height:1.4}p,ul,ol{margin:18px 0}.blog-copy ul,.blog-copy ol{padding-left:25px}li{margin:8px 0}a{color:#006ba6;text-decoration:underline;overflow-wrap:anywhere}figure{margin:30px 0}aside{font-size:14px;line-height:1.7;background:#f0f7fa;padding:24px;border-radius:14px;margin-top:36px}.sources{font-size:13px;overflow-wrap:anywhere}.sources ul{padding-left:20px}.article-table-scroll{overflow-x:auto;margin:24px 0}table{border-collapse:collapse;width:100%;font-size:14px;line-height:1.6}caption{text-align:left;font-weight:600;margin-bottom:12px}th,td{padding:12px;border:1px solid #dce6ed;vertical-align:top;text-align:left}th{background:#edf6f8}@media(max-width:760px){article{padding:26px 20px 50px}.intro{font-size:18px}.reading-layout{display:block}nav{position:static;max-height:none;padding:0;margin-bottom:24px;border-block:1px solid #dce6ed}nav summary{padding:14px 0}nav ol{columns:1}.hero{margin:24px 0}h2{font-size:27px}body{font-size:16px}}`;
